ALTER TABLE "Match" ADD COLUMN "scoreA" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Match" ADD COLUMN "scoreB" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Match" ADD COLUMN "resultType" TEXT;
ALTER TABLE "Match" ADD COLUMN "calledAt" TIMESTAMP(3);
ALTER TABLE "Match" ADD COLUMN "callCount" INTEGER NOT NULL DEFAULT 0;
